version: '3.4'

services:
  app:
    build:
      context: .
    working_dir: /app/example
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle-data:/usr/local/bundle
    ports:
      - "8080:3000"
    stdin_open: true
    tty: true

volumes:
  bundle-data: